export const DEFAULT_TEAMS = [
  { name: "Algeria", groupCode: "J", flagCode: "AL" },
  { name: "Argentina", groupCode: "J", flagCode: "AG" },
  { name: "Australia", groupCode: "D", flagCode: "AU" },
  { name: "Austria", groupCode: "J", flagCode: "AA" },
  { name: "Belgium", groupCode: "G", flagCode: "BG" },
  { name: "Bosnia and Herzegovina", groupCode: "B", flagCode: "BH" },
  { name: "Brazil", groupCode: "C", flagCode: "BZ" },
  { name: "Canada", groupCode: "B", flagCode: "CD" },
  { name: "Cape Verde", groupCode: "H", flagCode: "CV" },
  { name: "Colombia", groupCode: "K", flagCode: "CL" },
  { name: "Croatia", groupCode: "L", flagCode: "CR" },
  { name: "Curaçao", groupCode: "E", flagCode: "CA" },
  { name: "Czech Republic", groupCode: "A", flagCode: "CZ" },
  { name: "DR Congo", groupCode: "K", flagCode: "DR" },
  { name: "Ecuador", groupCode: "E", flagCode: "EC" },
  { name: "Egypt", groupCode: "G", flagCode: "EG" },
  { name: "England", groupCode: "L", flagCode: "EN" },
  { name: "France", groupCode: "I", flagCode: "FR" },
  { name: "Germany", groupCode: "E", flagCode: "GR" },
  { name: "Ghana", groupCode: "L", flagCode: "GH" },
  { name: "Haiti", groupCode: "C", flagCode: "HT" },
  { name: "Iran", groupCode: "G", flagCode: "IR" },
  { name: "Iraq", groupCode: "I", flagCode: "IQ" },
  { name: "Ivory Coast", groupCode: "E", flagCode: "IC" },
  { name: "Japan", groupCode: "F", flagCode: "JP" },
  { name: "Jordan", groupCode: "J", flagCode: "JD" },
  { name: "Mexico", groupCode: "A", flagCode: "MX" },
  { name: "Morocco", groupCode: "C", flagCode: "MR" },
  { name: "Netherlands", groupCode: "F", flagCode: "ND" },
  { name: "New Zealand", groupCode: "G", flagCode: "NZ" },
  { name: "Norway", groupCode: "I", flagCode: "NR" },
  { name: "Panama", groupCode: "L", flagCode: "PN" },
  { name: "Paraguay", groupCode: "D", flagCode: "PY" },
  { name: "Portugal", groupCode: "K", flagCode: "PG" },
  { name: "Qatar", groupCode: "B", flagCode: "QR" },
  { name: "Saudia Arabia", groupCode: "H", flagCode: "SU" },
  { name: "Scotland", groupCode: "C", flagCode: "SL" },
  { name: "Senegal", groupCode: "I", flagCode: "SN" },
  { name: "South Africa", groupCode: "A", flagCode: "SA" },
  { name: "South Korea", groupCode: "A", flagCode: "SK" },
  { name: "Spain", groupCode: "H", flagCode: "ES" },
  { name: "Sweden", groupCode: "F", flagCode: "SD" },
  { name: "Switzerland", groupCode: "B", flagCode: "SZ" },
  { name: "Tunisia", groupCode: "F", flagCode: "TS" },
  { name: "Turkey", groupCode: "D", flagCode: "TY" },
  { name: "Uruguay", groupCode: "H", flagCode: "UR" },
  { name: "USA", groupCode: "D", flagCode: "US" },
  { name: "Uzbekistan", groupCode: "K", flagCode: "UZ" },
] as const;
